name: pangenome-ml-data-generation
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<3.13
  - numpy
  - matplotlib
  - pandas
  - pillow
  - pysam
  - pybind11
  - pytorch>=2.1
  - torchvision>=0.16
  - "timm>=1.0,<2"
  - tqdm>=4.66
  - setuptools
  - wheel
  - jq
  - pip
  - pip:
      - protobuf==3.20.3
