"""Tables from scan/<chrom>.json (pon_scan.py): the somatic truth and the tensors of HG008T / COLO829T vs the 4 PoNs.

Writes pon_tables.md and truth_pon_<sample>.tsv (one row per truth allele: overlaps per PoN, AFs, recall status).
"""
import csv, json, sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

csv.field_size_limit(sys.maxsize)
HERE = Path(__file__).resolve().parent
DATA = Path("/scratch/jshen/data/pansoma_v2_tensors")
CHROMS = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]
AUTOSOMES = set(CHROMS[:22])
SETS = [("HG008T", "PacBio HiFi", "HG008T_PacBio"), ("HG008T", "ONT", "HG008T_ONT"), ("HG008T", "Illumina", "HG008T_Illumina"),
        ("COLO829T", "PacBio fiberseq", "COLO829T_fiberseq"), ("COLO829T", "ONT", "COLO829T_ONT"),
        ("COLO829T", "Illumina", "COLO829T_Illumina")]
LABEL_NAMES = {1: "1 somatic", 2: "2 germline", 0: "0 non", -1: "-1 ignore"}

scans = [json.loads((HERE / "scan" / f"{c}.json").read_text()) for c in CHROMS]
PON = scans[0]["pon_names"]
SHORT = [n.split("_", 1)[1] for n in PON]  # gnomAD, dbSNP, 1000G, CoLoRSdb


def fmt(n, total=None):
    return f"{n:,}" if total is None else (f"{n:,} ({100 * n / total:.1f}%)" if total else f"{n:,}")


def table(header, rows):
    numeric = [str(x).lstrip("*")[:1].isdigit() or str(x) == "-" for x in rows[0]]
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---:" if n else "---" for n in numeric) + "|"]
    return "\n".join(out + ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]) + "\n"


def kind_of(ref, alt):
    return "SNV" if len(ref) == 1 and len(alt) == 1 else "INDEL"


def names(bits):
    return "+".join(s for p, s in enumerate(SHORT) if bits >> p & 1) or "none"


# ---- truth alleles with recall status ------------------------------------------------------------------------------
truth = [t for s in scans for t in s["truth"]]
for t in truth:
    t["kind"] = kind_of(t["vcf_ref"], t["vcf_alt"])
status, truth_ids = {}, {}
for sample, platform, name in SETS:
    tt = {(r["chrom"], r["vcf_pos"], r["vcf_ref"], r["vcf_alt"]): r for r in
          csv.DictReader(open(DATA / name / "truth/somatic.graph.tsv"), delimiter="\t")}
    st = {r["truth_id"]: r["status"] for r in csv.DictReader(open(DATA / name / "tensors/somatic.recall.tsv"), delimiter="\t")}
    for t in truth:
        if t["sample"] != sample:
            continue
        row = tt.get((t["chrom"], str(t["vcf_pos"]), t["vcf_ref"], t["vcf_alt"]))
        if row is not None:
            t["truth_id"], t["in_bed"] = row["truth_id"], row["in_bed"] == "True"
            t[name] = st[row["truth_id"]]
missing_ids = sum(1 for t in truth if t["chrom"] in AUTOSOMES and "truth_id" not in t)

md = ["# Somatic truth and tensors vs the four PoN VCFs (generated by pon_tables.py)\n",
      "PoN rule = scripts/filter_panel_of_normals.py (repo, used by pansoma_net_v2.vcfeval): same POS, REF and ALT; "
      "gnomAD and CoLoRSdb only at ALT AF >= 1e-4; dbSNP only if not SAO=2; 1000G any. Looser overlaps: "
      "`position` = a PoN record starts at POS; `allele` = same POS/REF/ALT at any AF/SAO; `trimmed` = allele after "
      "removing the common suffix of REF and ALT (multi-allelic PoN records pad REF).\n",
      f"Truth alleles not found in the truth tables (should be 0): {missing_ids}.\n"]

# ---- 1. truth overlap ----------------------------------------------------------------------------------------------
md.append("## 1. Somatic truth alleles in the PoNs (any of the four)\n")
rows = []
for sample in ("HG008T", "COLO829T"):
    for where in ("chr1-22", "chrX/Y"):
        for kind in ("SNV", "INDEL"):
            sel = [t for t in truth if t["sample"] == sample and t["kind"] == kind
                   and ((t["chrom"] in AUTOSOMES) == (where == "chr1-22"))]
            if not sel:
                continue
            n = len(sel)
            rows.append([sample, where, kind, fmt(n), fmt(sum(t["position"] > 0 for t in sel), n),
                         fmt(sum(t["allele"] > 0 for t in sel), n), fmt(sum(t["trimmed"] > 0 for t in sel), n),
                         fmt(sum(t["rule"] > 0 for t in sel), n)])
md.append(table(["Sample", "Chromosomes", "Kind", "truth alleles", "position overlap", "allele overlap (any AF)",
                 "trimmed-allele overlap", "**tagged by the PoN rule**"], rows))

md.append("## 2. Per PoN (chr1-22 truth alleles)\n")
rows = []
for sample in ("HG008T", "COLO829T"):
    for kind in ("SNV", "INDEL"):
        sel = [t for t in truth if t["sample"] == sample and t["kind"] == kind and t["chrom"] in AUTOSOMES]
        n = len(sel)
        for p, s in enumerate(SHORT):
            b = 1 << p
            only = sum(t["rule"] == b for t in sel)
            rows.append([sample, kind, s, fmt(sum(t["position"] & b > 0 for t in sel), n),
                         fmt(sum(t["allele"] & b > 0 for t in sel), n), fmt(sum(t["trimmed"] & b > 0 for t in sel), n),
                         fmt(sum(t["rule"] & b > 0 for t in sel), n), fmt(only)])
md.append(table(["Sample", "Kind", "PoN", "position overlap", "allele overlap (any AF)", "trimmed-allele overlap",
                 "tagged by its rule", "tagged by this PoN only"], rows))

md.append("## 3. Which PoNs tag a truth allele (rule, chr1-22)\n")
rows = []
for sample in ("HG008T", "COLO829T"):
    for kind in ("SNV", "INDEL"):
        sel = [t for t in truth if t["sample"] == sample and t["kind"] == kind and t["chrom"] in AUTOSOMES and t["rule"]]
        combos = Counter(names(t["rule"]) for t in sel)
        rows.append([sample, kind, fmt(len(sel)), "; ".join(f"{k} {v:,}" for k, v in combos.most_common())])
md.append(table(["Sample", "Kind", "tagged", "PoN combinations"], rows))

md.append("## 4. Population AF of the truth alleles found in gnomAD / CoLoRSdb (allele overlap, chr1-22)\n")
md.append("AF < 1e-4 is below the rule's floor (overlap but not tagged).\n")
edges = [0, 1e-4, 1e-3, 1e-2, 0.1, 1.01]
bnames = ["<1e-4", "1e-4 - 1e-3", "1e-3 - 0.01", "0.01 - 0.1", ">=0.1"]
rows = []
for sample in ("HG008T", "COLO829T"):
    for kind in ("SNV", "INDEL"):
        for p in (0, 3):
            v = [t["af"][p] for t in truth if t["sample"] == sample and t["kind"] == kind and t["chrom"] in AUTOSOMES
                 and t["allele"] >> p & 1 and t["af"][p] is not None]
            h = np.histogram(v, edges)[0] if v else [0] * 5
            rows.append([sample, kind, SHORT[p], fmt(len(v))] + [fmt(int(x)) for x in h]
                        + [f"{np.median(v):.2e}" if v else "-"])
md.append(table(["Sample", "Kind", "PoN", "allele overlap with AF"] + bnames + ["median AF"], rows))

# ---- 5. PoN effect on the tensor recall ----------------------------------------------------------------------------
md.append("## 5. PoN effect on the truth built into tensors (recall ceiling before / after the PoN)\n")
md.append("`built` = the truth allele is in a tensor (representative or other allele); after the PoN it counts only "
          "if the PoN rule does not tag the allele (the tensor's GRCh38 allele is the truth allele). chr1 in BED = the "
          "set vcfeval scores (HG008T; COLO829T has no restricting BED).\n")
rows = []
for sample, platform, name in SETS:
    for kind in ("SNV", "INDEL"):
        for label, cond in (("chr1-22", lambda t: t["chrom"] in AUTOSOMES), ("chr1", lambda t: t["chrom"] == "chr1"),
                            ("chr1 in BED", lambda t: t["chrom"] == "chr1" and t.get("in_bed"))):
            if sample == "COLO829T" and label == "chr1 in BED":
                continue
            sel = [t for t in truth if t["sample"] == sample and t["kind"] == kind and cond(t) and name in t]
            n = len(sel)
            built = [t for t in sel if t[name].startswith("tensor")]
            tagged = sum(t["rule"] > 0 for t in sel)
            kept = sum(t["rule"] == 0 for t in built)
            rows.append([sample, platform, kind, label, fmt(n), fmt(tagged, n), fmt(len(built), n), fmt(len(built) - kept),
                         fmt(kept, n)])
md.append(table(["Sample", "Platform", "Kind", "truth set", "truth alleles", "tagged by the PoN (any caller loses)",
                 "built (before PoN)", "built but tagged", "**built and kept (after PoN)**"], rows))

md.append("## 5b. PoN tag of the truth alleles by recall status and miss class (chr1-22)\n")
md.append("Missed truth alleles already in the HPRC graph (I1/I2, S3) are often population alleles, so the PoN would "
          "remove them anyway. Classes from ../per_truth_<sample>.tsv (recall_tables.py).\n")
classes = {}
for sample in ("HG008T", "COLO829T"):
    path = HERE.parent / f"per_truth_{sample}.tsv"
    if path.exists():
        for r in csv.DictReader(open(path), delimiter="\t"):
            for name in [n for s_, _, n in SETS if s_ == sample]:
                classes[(name, r["truth_id"])] = r.get(f"{name.split('_', 1)[1]}_class", "")
rows = []
for sample, platform, name in SETS:
    for kind, kinds in (("SNV", ("SNV",)), ("INS", ("INS",)), ("DEL", ("DEL",))):
        sel = [t for t in truth if t["sample"] == sample and t["chrom"] in AUTOSOMES and name in t]
        groups = defaultdict(list)
        for t in sel:
            k = "SNV" if t["kind"] == "SNV" else ("INS" if len(t["vcf_alt"]) > len(t["vcf_ref"]) else "DEL")
            if k != kind:
                continue
            st = t[name]
            g = "built" if st.startswith("tensor") else "filtered" if st == "filtered" else "no candidate"
            groups[g].append(t)
            if g == "no candidate":
                c = classes.get((name, t["truth_id"]), "") or "pending"
                groups["  no candidate " + c.split("_")[0]].append(t)
        for g in sorted(groups, key=lambda g: (g.startswith("  "), {"built": 0, "filtered": 1, "no candidate": 2}.get(g, 3), g)):
            ts = groups[g]
            rows.append([sample, platform, kind, g, fmt(len(ts)), fmt(sum(t["rule"] > 0 for t in ts), len(ts))])
md.append(table(["Sample", "Platform", "Kind", "recall status / miss class", "truth alleles", "tagged by the PoN"], rows))

# ---- 6. PoN effect on the tensors ----------------------------------------------------------------------------------
md.append("## 6. PoN effect on the tensors by label (chr1-22)\n")
md.append("Placed = the tensor has a GRCh38 allele (the PoN can only see those; off-reference and no-unique-node tensors "
          "are unplaced). Tagged = % of placed tensors the PoN rule tags; for label 2 that is germline removed (wanted), "
          "for label 1 somatic removed (unwanted).\n")
agg = defaultdict(Counter)  # (name, kind, label, chrom scope) -> counts
by_reason = defaultdict(Counter)  # label-1 tensors: (name, kind, reason) -> placed / tagged (chr1-22)
for s in scans:
    for name, kind, label, reason, bits, c in s["tensors"]:
        for scope in ("chr1-22",) + (("chr1",) if s["chrom"] == "chr1" else ()):
            g = agg[(name, kind, label, scope)]
            g["n"] += c
            if bits == "unplaced":
                g["unplaced"] += c
                continue
            pos_bits, allele_bits, rule_bits = map(int, bits.split(":"))
            g["allele"] += c * (allele_bits > 0)
            g["rule"] += c * (rule_bits > 0)
            for p in range(4):
                g[f"rule{p}"] += c * (rule_bits >> p & 1)
            if label == 1 and scope == "chr1-22":
                by_reason[(name, kind, reason)]["n"] += c
                by_reason[(name, kind, reason)]["rule"] += c * (rule_bits > 0)
for scope in ("chr1-22", "chr1"):
    rows = []
    for sample, platform, name in SETS:
        for kind in ("SNV", "INDEL"):
            for label in (1, 2, 0, -1):
                g = agg[(name, kind, label, scope)]
                placed = g["n"] - g["unplaced"]
                rows.append([sample, platform, kind, LABEL_NAMES[label], fmt(g["n"]), fmt(g["unplaced"], g["n"]),
                             fmt(g["allele"], placed), fmt(g["rule"], placed)]
                            + [fmt(g[f"rule{p}"], placed) for p in range(4)])
    md.append(f"**{scope}**\n")
    md.append(table(["Sample", "Platform", "Kind", "label", "tensors", "unplaced", "allele in a PoN (any AF)",
                     "**tagged (rule)**"] + [f"tagged by {s}" for s in SHORT], rows))

md.append("Label-1 tensors by reason (chr1-22): tagged share of the placed ones\n")
rows = []
for sample, platform, name in SETS:
    for kind in ("SNV", "INDEL"):
        for (n_, k_, reason), g in sorted(by_reason.items()):
            if n_ == name and k_ == kind:
                rows.append([sample, platform, kind, reason, fmt(g["n"]), fmt(g["rule"], g["n"])])
md.append(table(["Sample", "Platform", "Kind", "reason", "placed label-1 tensors", "tagged"], rows))

ref_mismatch = Counter()
for s in scans:
    ref_mismatch.update(s["ref_mismatch"])
md.append(f"Tensors whose GRCh38 REF differs from the FASTA (counted as unplaced; linear_vcf would stop): "
          f"{dict(ref_mismatch) or 0}.\n")
(HERE / "pon_tables.md").write_text("\n".join(md))

for sample in ("HG008T", "COLO829T"):
    sets = [name for s, _, name in SETS if s == sample]
    with open(HERE / f"truth_pon_{sample}.tsv", "w") as out:
        out.write("\t".join(["truth_id", "chrom", "vcf_pos", "vcf_ref", "vcf_alt", "kind", "in_bed", "position", "allele",
                             "trimmed", "rule"] + [f"{s}_AF" for s in SHORT] + [f"{n}_status" for n in sets]) + "\n")
        for t in truth:
            if t["sample"] != sample:
                continue
            out.write("\t".join(str(x) for x in [t.get("truth_id", ""), t["chrom"], t["vcf_pos"], t["vcf_ref"], t["vcf_alt"],
                                                 t["kind"], t.get("in_bed", ""), names(t["position"]), names(t["allele"]),
                                                 names(t["trimmed"]), names(t["rule"])]
                               + ["" if a is None else a for a in t["af"]] + [t.get(n, "") for n in sets]) + "\n")
print((HERE / "pon_tables.md").read_text())
