"""Tables of the INDEL PoN rules (pon_features.RULES) over scan/chr*.json: truth INDELs, recall ceilings, tensors by label.

chr2-22 and chr1 are reported apart: chr1 is the pansoma_net_v2 test chromosome (calls_chr1.py scores the chr1 calls),
chr2-22 is where a rule should be chosen. Writes rules_tables.md.
"""
import csv, json, sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from pon_features import RULES, as_dict  # noqa: E402

csv.field_size_limit(sys.maxsize)
CHROMS = [f"chr{i}" for i in range(1, 23)]
SETS = [("HG008T", "PacBio", "HG008T_PacBio"), ("HG008T", "ONT", "HG008T_ONT"), ("HG008T", "Illumina", "HG008T_Illumina"),
        ("COLO829T", "fiberseq", "COLO829T_fiberseq"), ("COLO829T", "ONT", "COLO829T_ONT"),
        ("COLO829T", "Illumina", "COLO829T_Illumina")]
SCOPES = ("chr2-22", "chr1")
scans = {c: json.loads((HERE / "scan" / f"{c}.json").read_text()) for c in CHROMS}
feat_cache = {}


def fd(t):
    t = tuple(t)
    if t not in feat_cache:
        feat_cache[t] = as_dict(t)
    return feat_cache[t]


def scope_of(chrom):
    return "chr1" if chrom == "chr1" else "chr2-22"


def pct(n, d):
    return f"{100 * n / d:.1f}%" if d else "-"


# truth INDEL alleles with the per-platform recall status (per_truth_<sample>.tsv of recall_tables.py)
status = {}
for sample in ("HG008T", "COLO829T"):
    for r in csv.DictReader(open(HERE.parents[1] / f"per_truth_{sample}.tsv"), delimiter="\t"):
        status[(sample, r["chrom"], r["vcf_pos"], r["vcf_ref"], r["vcf_alt"])] = r
truth = []
for c, s in scans.items():
    for t in s["truth"]:
        t["chrom"] = c
        t["row"] = status.get((t["sample"], c, str(t["vcf_pos"]), t["vcf_ref"], t["vcf_alt"]))
        truth.append(t)
missing = sum(t["row"] is None for t in truth)

# tensors: (set, label, scope, feature tuple or None) -> count
tensors = Counter()
for c, s in scans.items():
    for name, label, reason, f, n in s["tensors"]:
        tensors[(name, label, scope_of(c), None if f == "unplaced" else tuple(map(int, f.split(","))))] += n

md = ["# INDEL PoN rules compared (generated by rules_tables.py)\n",
      "Rules: see pon_features.py. Truth = the somatic truth INDEL alleles as VCF records; tensors = INDEL tensors with a "
      "GRCh38 allele (unplaced ones cannot be tagged by any PoN). Percent = tagged share.\n",
      f"Truth alleles without a per_truth row (should be 0): {missing}.\n"]

# ---- 1. truth tagged --------------------------------------------------------------------------------------------
md.append("## 1. Somatic truth INDELs tagged by each rule\n")
head = ["rule"] + [f"{s} {sc}" for s in ("HG008T", "COLO829T") for sc in SCOPES]
rows = []
for name, rule in RULES.items():
    row = [name]
    for sample in ("HG008T", "COLO829T"):
        for sc in SCOPES:
            sel = [t for t in truth if t["sample"] == sample and scope_of(t["chrom"]) == sc]
            row.append(f"{sum(rule(fd(t['feat'])) for t in sel):,} / {len(sel):,} ({pct(sum(rule(fd(t['feat'])) for t in sel), len(sel))})")
    rows.append(row)
md += ["| " + " | ".join(head) + " |", "|---|" + "---:|" * (len(head) - 1)] + ["| " + " | ".join(r) + " |" for r in rows] + [""]

# ---- 2. recall ceiling after each rule ---------------------------------------------------------------------------
md.append("## 2. INDEL recall ceiling after each rule (built and not tagged / truth alleles), chr2-22\n")
head = ["rule"] + [f"{s} {p}" for s, p, _ in SETS]
rows = [["(built, no PoN)"]]
for s, p, name in SETS:
    sel = [t for t in truth if t["sample"] == s and scope_of(t["chrom"]) == "chr2-22" and t["row"]]
    built = sum(t["row"][f"{name.split('_', 1)[1]}_status"].startswith("tensor") for t in sel)
    rows[0].append(pct(built, len(sel)))
for rname, rule in RULES.items():
    row = [rname]
    for s, p, name in SETS:
        sel = [t for t in truth if t["sample"] == s and scope_of(t["chrom"]) == "chr2-22" and t["row"]]
        kept = sum(t["row"][f"{name.split('_', 1)[1]}_status"].startswith("tensor") and not rule(fd(t["feat"])) for t in sel)
        row.append(pct(kept, len(sel)))
    rows.append(row)
md += ["| " + " | ".join(head) + " |", "|---|" + "---:|" * (len(head) - 1)] + ["| " + " | ".join(r) + " |" for r in rows] + [""]

# ---- 3. tensors by label -----------------------------------------------------------------------------------------
md.append("## 3. INDEL tensors tagged by each rule, by label (placed tensors)\n")
md.append("1 = somatic lost (unwanted), 2 = germline removed (wanted), 0 = non removed. Per set: label 1 / label 2 / label 0.\n")
for sc in SCOPES:
    for sample in ("HG008T", "COLO829T"):
        sets = [(p, name) for s, p, name in SETS if s == sample]
        head = ["rule"] + [f"{p}: 1 / 2 / 0" for p, _ in sets]
        rows = []
        totals = {}
        for p, name in sets:
            for label in (1, 2, 0):
                totals[(name, label)] = sum(n for (nm, lb, s_, f), n in tensors.items() if nm == name and lb == label and s_ == sc and f is not None)
        rows.append(["(placed tensors)"] + [" / ".join(f"{totals[(name, l)]:,}" for l in (1, 2, 0)) for _, name in sets])
        for rname, rule in RULES.items():
            row = [rname]
            for p, name in sets:
                cells = []
                for label in (1, 2, 0):
                    tagged = sum(n for (nm, lb, s_, f), n in tensors.items()
                                 if nm == name and lb == label and s_ == sc and f is not None and rule(fd(f)))
                    cells.append(pct(tagged, totals[(name, label)]))
                row.append(" / ".join(cells))
            rows.append(row)
        md.append(f"**{sample}, {sc}**\n")
        md += ["| " + " | ".join(head) + " |", "|---|" + "---:|" * (len(head) - 1)] + ["| " + " | ".join(r) + " |" for r in rows] + [""]

# ---- 4. why a population-AF floor separates somatic from germline -------------------------------------------------
md.append("## 4. Highest population AF of the exact allele (max of gnomAD and CoLoRSdb), chr1-22\n")
md.append("Truth INDELs vs germline (label 2) and non (label 0) INDEL tensors. A floor tags everything at or above it.\n")
bn = ["not in gnomAD/CoLoRSdb", "<1e-4", "1e-4 - 1e-3", "1e-3 - 0.01", "0.01 - 0.05", "0.05 - 0.1", ">=0.1"]


def pop_bucket(f):
    return max(f[1], f[12])  # g_af, c_af


rows = []
for sample in ("HG008T", "COLO829T"):
    h = Counter(pop_bucket(t["feat"]) for t in truth if t["sample"] == sample)
    n = sum(h.values())
    rows.append([f"{sample} somatic truth", f"{n:,}"] + [pct(h[b], n) for b in range(-1, 6)])
for s, p, name in SETS:
    for label, lname in ((2, "germline tensors"), (0, "non tensors")):
        h = Counter()
        for (nm, lb, s_, f), c in tensors.items():
            if nm == name and lb == label and f is not None:
                h[pop_bucket(f)] += c
        n = sum(h.values())
        rows.append([f"{s} {p} {lname}", f"{n:,}"] + [pct(h[b], n) for b in range(-1, 6)])
md += ["| set | alleles | " + " | ".join(bn) + " |", "|---|---:|" + "---:|" * len(bn)] + ["| " + " | ".join(r) + " |" for r in rows] + [""]
(HERE / "rules_tables.md").write_text("\n".join(md) + "\n")
print((HERE / "rules_tables.md").read_text())
